### ISSUE TITLE
tarvitaan risk free rate

### ISSUE THREAD

**Issue by tsili** [tsili/cf-case-ponsse#1]
halutaanko laskea vai olettaa

**Comment by emmakontsas** [comment]
voitais varmaan olettaa

**Comment by tsili** [comment]
Mikä me halutaan olettaa risk free raten olevan?

**Comment by topi93** [comment]
PWCn kyselytutkimuksen mukaan riskipreemio 2015 5,8%.
Lisäksi monet lisää siihen preemioo jos on pieni tai epälikvidi firma.
Toi on varmaan ihan fiksu olettaa riskipreemioks. Veikkaan et jos lasketaan historiallisesti tulee korkeampi. Mut kysymys herää, että lisätäänkö Ponsselle koon tai likividiteetin takia preemiota?

**Comment by topi93** [comment]
Oletetaan 0%

**Comment by tsili** [comment]
risk free rate 0% lisätty tietoihin.
