### ISSUE TITLE
Osinkohistoria

### ISSUE THREAD

**Issue by topi93** [tsili/cf-case-ponsse#12]
http://www.kauppalehti.fi/5/i/porssi/osingot/osinkohistoria.jsp?klid=1046

**Comment by topi93** [comment]
OSINKOPOLITIIKKA:
Yhtiö noudattaa osingonjakopolitiikkaa, jossa osinkoa jaetaan
yhtiön pitkäaikaisen tuloskehityksen ja pääomavaatimusten
mukaisesti.

**Comment by tsili** [comment]
Kuka haluaa tehdä osinkotaulukon?
