### ISSUE TITLE
Riskipreemio

### ISSUE THREAD

**Issue by topi93** [tsili/cf-case-ponsse#2]
www.pwc.fi/fi/julkaisut/tiedostot/markkinariskipreemio_2012.pdf

**Comment by tsili** [comment]
β #5 tarvitaan Ponssen riskipreemiota varten

**Comment by topi93** [comment]
PWCn kyselytutkimuksen mukaan riskipreemio 2015 5,8%.
Lisäksi monet lisää siihen preemioo jos on pieni tai epälikvidi firma.
Toi on varmaan ihan fiksu olettaa riskipreemioks. Veikkaan et jos lasketaan historiallisesti tulee korkeampi. Mut kysymys herää, että lisätäänkö Ponsselle koon tai likividiteetin takia preemiota?

**Comment by topi93** [comment]
Sovittiin, että käytetään 5,8%

**Comment by emmakontsas** [comment]
Käytetäänkin 5,8 + 3,2 = 9 %

**Comment by tsili** [comment]
riskipreemiota tulee korjata β:lla ja lisätä likviditeettipreemio

**Comment by tsili** [comment]
tehty ja laitettu kaavoineen kansioon cost-of-equity #19
