### ISSUE TITLE
ponsse kuvaus ja tila

### ISSUE THREAD

**Issue by tsili** [tsili/cf-case-ponsse#4]
Kurssin mukaan tila ainakin näyttäis hyvältä, mutta pitäs kattoo tarkemmin

**Comment by tsili** [comment]
kurssi löytyy [täältä](http://finance.yahoo.com/quote/PON1V.HE?ltr=1)

**Comment by topi93** [comment]
https://finance.yahoo.com/quote/DE/?p=DE

Tossa yks verrokki
