### ISSUE TITLE
Ponssen β

### ISSUE THREAD

**Issue by tsili** [tsili/cf-case-ponsse#5]
Ponssen β tarvitaan useita laskuja varten

**Comment by tsili** [comment]
Halutaanko laskea β staattisena lukuna vai uskotaanko sen muuttuvan ajan kanssa?
Jos halutaan muuttuminen uskoa, niin mitkä aikajaksot pitäisi laskea; päivä, viikko, kuukausi, vuosi, vai vuosikymmen β.

**Comment by topi93** [comment]
Oisko silleen et tämän hetken Beta staattisena, mut voitais vähän kattoo miten se on aikojen saatossa kehittynyt tähän päivään?

**Comment by TonyHurm** [comment]
Nii siis eikö me lasketa beta esim 20 edelliseltä vuodelta ja sit voidaa esim laskee viel 10, 5 ja yhen vuoden betat. Riippuen nyt kuinka pitkält ajalta me saadaa dataa. Siit en osaa sanoo et millä perusteel me valitaa mitä betaa me käytetää.

**Comment by tsili** [comment]
Ei oo tarjolla indexidataa niin kaukaa. 17 vuotta saatas OMXHCAPPI:stä

**Comment by tsili** [comment]
indeksi ja hintadata ladattu. Kuka haluaa lähtee laskeen β?

**Comment by TonyHurm** [comment]
Mä voin yrittää.

**Comment by TonyHurm** [comment]
Miks noita havaintoja on enemmän tos indeksis ku ponssella. Meil pitäs olla sama määrä noita.

**Comment by tsili** [comment]
Nyt mä en ihan ymmärrä, sama aikajakso molemmissa pitäisi olla, vai puuttuuko toisesta välistä jotain? Voikko antaa esimerkin poikkeamasta.

**Comment by TonyHurm** [comment]
No indexissä on yli 4200 havaintoo ja ponssella vaa vähän päälle 4000. En mäkää ymmärrä mistä se ero tulee enkä kyl oikee jaksas käydäkkää joka ikistä päivää läpi.

**Comment by tsili** [comment]
Okei sain selville. Eli joiltain päiviltä on dataa vain toiselta. Tarkistin asian nasdaqista ja se on ilmeisesti oikein. Silloin kun näin käy, laske välipäivän arvo lineaarisena suhteena viimeisimmän datapisteen ja seuraavan välillä.

Esim Ponsselta puuttuu data väliltä 2003/06/11-2003/06/16. Joten lasketaan ne pisteet
11: 51,20
16: 52,20

välissä: 12, 13 14, 15
ero: 1
hyppy: ero / ( välilukujen määrä + 1 ): 0,20

11: 51,20
12: 51,40
13: 51,60
14: 51,80
15: 52;00
16: 52,20

Voit laittaa jonkin makron tekeen ton automaattisesti excelissä, ettei tartte manuaalisesti tehdä.

**Comment by TonyHurm** [comment]
Ok. En kyl osaa makroi käyttää ollenkaa ja en tiiä miten saisin excelin löytää noi puuttuvat päivät. Jos katotaa huomen tapaamises tota tai jos Lauri sult luonnistuu toi nopeesti ni tee vaa. Mun excel taidot alkaa loppuu.

**Comment by tsili** [comment]
beta lisätty #15.
