### ISSUE TITLE
Seuraava tapaaminen

### ISSUE THREAD

**Issue by tsili** [tsili/cf-case-ponsse#6]
Milloin pitäisi tavata ja mistä pitäisi puhua?

Oma ensiviikon ok-aika lista on seuraava:
MA 8-10
TI 14-16 ja 18-
KE 8-10
TO 16-
PE 10-12

**Comment by TonyHurm** [comment]
Kaikki paitsi perjantai noista ajoista käy

**Comment by tsili** [comment]
Eli mistä olisi tarkoitus edes keskustella? Sen mukaan mitä täältä löytyy, niin kukaan ei ole vielä tehnyt mitään. Ehdotan siis mieluummin tiistaita ja väki oikeasti tekisikin jotain. Muuten koko tapaaminen on aivan tyhjän kanssa. En ainakaan usko että kukaan haluaa nousta maanantaina 6-7 vain kuullakseen, ettei mikään ole muuttunut.

Oon laittanut useita ongelmia ylös #1 #4 #5 ja toivoisin hieman inputtia, että pääsen jatkamaan eteenpäin.

**Comment by emmakontsas** [comment]
Ehkä turha nyt alkuviikosta vielä, toi torstai klo 16 vois olla hyvä, ei oo ainakaan sen jälkeen mitään niin ehtis kyllä sit jäädä ihan porukallakin miettimään ja selvittämään. Jos nyt kaikki siihen mennessä vaikka lukis siitä Ponssesta et on vähän tietoa kohtiin 1 ja 2 ja sit vois miettiä et mitä risk free rate ja vaik beta. Oisko sellanen hyvä plääni? Ei pitäis olla liian ylivoimaista tehä torstaihin mennessä!

**Comment by topi93** [comment]
Mulla on torstaina tollain Investmentsin harkka. Se loppuu toki kuudelta et sen jälkeen kyllä käy. Emman ehdotus on ihan fiksu. Kaikki vähän lukis ja analysois ja sit kyl tarvitaan se tapaaminen, et saadaan potkittua homma alulle.

**Comment by emmakontsas** [comment]
Ehkä sit perjantai vois olla parempi, mul on sillon koko päivä tyhjää että joskus päiväsaikaan vois olla hyvä. Tony sano et pe ei oikeen kävis mut käyks joku muu aika kun noi tossa? Vaik joskus iltapäivällä?

**Comment by topi93** [comment]
Perjantai käy mulle kympistä eteenpäin

**Comment by TonyHurm** [comment]
Mulle käy 12 eteenpäi

**Comment by tsili** [comment]
Jos @TonyHurm käy vasta 12 eteenpäin, niin silloin ei perjantai oikein onnistu. Pakko vaan yrittää silloin torstaina @topi93 harkkojen jälkeen.

**Comment by topi93** [comment]
Torstaina 18 alkaen it is!
Kaikille nyt varmasti ok?

**Comment by emmakontsas** [comment]
Voi jeesus D: mul on 9-12 enkkuu eikä muuta ja pitäis johonki seiskaan asti jaksaa olla koulul X( kai mä jotain keksin siihen sit.. nähää kuudelt innovaatiotilas, en pysty olee tuntii pidempään paikalla koska haluun bussilla kotiin!
