### ISSUE TITLE
Markkina indeksi

### ISSUE THREAD

**Issue by tsili** [tsili/cf-case-ponsse#7]
Mikä on ponssen markkina indeksi? En oo ihan varma voidaanko olettaa vaan S&P 500 vai pitäiskö sen olla jokin muu. Se on kuitenkin olennainen osa β laskentaa. Tarvitaanko myös erikseen metsä-alan indeksi ja konepaja-alan indeksi? niillekin tarvittaisiin silloin omat β laskelmat.

**Comment by topi93** [comment]
Mun mielestä tohon Betan laskentaan pitäis käyttää helsingin pörssin indeksiä.

**Comment by tsili** [comment]
Voikko heittää pikasen linkin sen aikasarjaan @topi93 ? Saatais siitä jotain silloin laskettuakin.

**Comment by topi93** [comment]
http://www.kauppalehti.fi/5/i/porssi/porssikurssit/indeksi.jsp?indid=OMXHCAPPI&days=max&x=31&y=12

Saiskohan tosta miten hyvin dataa?

**Comment by TonyHurm** [comment]
http://www.nasdaqomxnordic.com/indeksit/historialliset_kurssitiedot?Instrument=FI0008900238

tosta

**Comment by tsili** [comment]
Ok, eli mä käyn lataamassa ne 20 vuotta dataa tänne.

**Comment by tsili** [comment]
Ei onnistukkaa. OMXHCAPGI alkaa Jun, 1, 2011 ja OMXHCAPPI Jan, 4, 1999. Riittäiskö OMXHCAPPI:n data? Jos ottais 1999/11/01-2016/10/31, niin saatais 17 vuotta.

**Comment by topi93** [comment]
Eiköhän toi riitä. Mun mielestä toi Cappi indeksi on kuitenki parempi omx25. Mistä lähteestä muuten kattelet tota dataa?

**Comment by tsili** [comment]
http://www.nasdaqomxnordic.com/index/index_info?Instrument=FI0008900014 löytyy omxhcappi

**Comment by tsili** [comment]
#8 OMXHCAPPI Indeksin tiedot ladattu ajalta 1999/11/1-2016/10/31
